# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9ac155e0e158cf421c941d0ca4bc56d00d0809609a28a0013c534c984296965ab41c8c4dd49b88a0ee8521d3ad4f968061372c17d59aa843c8cf6342cccbed8

test:
  secret_key_base: 2baec8846ff9a68e2009402257c315f8a5af6dff5a59c46889b5d503a5623b4daa375a85e491b00adf404a7ca0afb93a1e206d7bbd1396a7df7f82448cde0c95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
